"""PDF report generation using fpdf2."""
import io
from datetime import datetime
from typing import Optional
from app.schemas.analysis import AnalysisResult


def generate_pdf_report(result: AnalysisResult) -> bytes:
    """Generate a clinical PDF report. Returns bytes."""
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Header
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_fill_color(15, 23, 42)
        pdf.set_text_color(255, 255, 255)
        pdf.rect(0, 0, 210, 35, "F")
        pdf.set_xy(10, 10)
        pdf.cell(0, 10, "Multimodal Video Health AI", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_xy(10, 22)
        pdf.cell(0, 6, "Movement Analysis Report", ln=True)

        pdf.set_text_color(0, 0, 0)
        pdf.set_xy(10, 40)

        # Meta
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, f"Session ID: {result.session_id}    |    Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}    |    Exercise: {result.exercise_type.title()}", ln=True)
        pdf.ln(4)

        # Risk banner
        risk_colors = {"low": (34, 197, 94), "medium": (234, 179, 8), "high": (239, 68, 68)}
        r, g, b = risk_colors.get(result.overall_risk, (100, 100, 100))
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, f"  Overall Risk: {result.overall_risk.upper()}", ln=True, fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

        # Biomechanics metrics
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Biomechanical Metrics", ln=True)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        bm = result.biomechanics
        metrics = [
            ("Frames Analysed", str(result.frames_processed)),
            ("Video Duration", f"{result.duration_sec:.1f} sec"),
            ("Knee Angle (avg)", f"{bm.knee_angle}°" if bm.knee_angle else "—"),
            ("Hip Angle (avg)", f"{bm.hip_angle}°" if bm.hip_angle else "—"),
            ("Spine Deviation", f"{bm.spine_deviation:.4f}" if bm.spine_deviation else "—"),
            ("Asymmetry Score", f"{bm.asymmetry_score:.4f}" if bm.asymmetry_score else "—"),
        ]
        pdf.set_font("Helvetica", "", 10)
        col_w = 90
        for label, value in metrics:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(col_w, 7, label)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(col_w, 7, value, ln=True)
        pdf.ln(4)

        # Alerts
        if bm.alerts:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, "Biomechanical Alerts", ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
            pdf.set_fill_color(254, 226, 226)
            pdf.set_font("Helvetica", "", 10)
            for alert in bm.alerts:
                pdf.set_fill_color(254, 226, 226)
                pdf.cell(0, 7, f"  {alert}", ln=True, fill=True)
                pdf.ln(1)
            pdf.ln(3)

        # AI Summary
        if result.ai_summary:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, "Clinical Summary", ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
            pdf.set_fill_color(239, 246, 255)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, result.ai_summary, fill=True)
            pdf.ln(4)

        # Recommendations
        if result.recommendations:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, "Recommendations", ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
            pdf.set_font("Helvetica", "", 10)
            for i, rec in enumerate(result.recommendations, 1):
                pdf.cell(8, 7, f"{i}.")
                pdf.multi_cell(0, 7, rec)
            pdf.ln(4)

        # Transcript
        if result.transcript:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 8, "Audio Transcript", ln=True)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(3)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, result.transcript)
            pdf.ln(4)

        # Footer
        pdf.set_text_color(150, 150, 150)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_y(-15)
        pdf.cell(0, 5, "Generated by Multimodal Video Health AI — github.com/devkapil-tech/multimodal-video-health-ai — Not a substitute for professional medical advice", align="C")

        return pdf.output()

    except ImportError:
        # fpdf2 not installed — return a simple text fallback as bytes
        lines = [
            "MULTIMODAL VIDEO HEALTH AI — ANALYSIS REPORT",
            f"Session: {result.session_id}  |  Exercise: {result.exercise_type}  |  Risk: {result.overall_risk.upper()}",
            "",
            f"Frames: {result.frames_processed}  Duration: {result.duration_sec:.1f}s",
            f"Knee: {result.biomechanics.knee_angle}°  Hip: {result.biomechanics.hip_angle}°",
            "",
            "ALERTS:",
            *[f"  - {a}" for a in result.biomechanics.alerts],
            "",
            "SUMMARY:",
            result.ai_summary or "N/A",
            "",
            "RECOMMENDATIONS:",
            *[f"  {i+1}. {r}" for i, r in enumerate(result.recommendations)],
        ]
        return "\n".join(lines).encode("utf-8")
